
[welcome_message]
	#Enable or disable the welcome message
	enabled = true
	#The message to be displayed when a player joins the game for the first time
	text = "THANKS TO OUR SPONSORS, ZAP-HOSTING! Support Reggarf And Save BIG - USE CODE Reggarf-1047 FOR 20% OFF Your ORDER!"
	#The RGB color code for the welcome message.
	#Examples: 'FF0000' for red, '00FF00' for green, '0000FF' for blue
	#'FFFF00' for yellow, 'FF00FF' for magenta, '00FFFF' for cyan
	color = "FFFFFF"
	#The URL to be opened when the player clicks the link
	url = "https://zap-hosting.com/reggarf"
	#The RGB color code for the clickable text '[Click here]',
	#Examples: 'FF0000' for red, '00FF00' for green, '0000FF' for blue
	#'FFFF00' for yellow, 'FF00FF' for magenta, '00FFFF' for cyan, 'FFFFFF' for white
	clickableColor = "00FFAA"

